### ISSUE TITLE
Support owner / group file permissions

### ISSUE THREAD

**Issue by petehayes** [nanliu/puppet-archive#22]
In nanliu-staging, it was possible to set the owner and group when deploying an archive.  I couldn't find similar support in nanliu-archive.  Could this support be added?

**Comment by nanliu** [comment]
Not sure the best way to implement this. Originally was going to add this in the provider code but it felt like feature creep since it overlaps with the file resource. For now, the owner/group management can be specified in a define resource similar to https://github.com/nanliu/puppet-archive/blob/master/manifests/go.pp.

Writing a generic define resource wrapper is pretty straightforward, I'm not sure what's a good name (archive::file ???).

**Comment by petehayes** [comment]
The owner/group management in go.pp and artifactory.pp sets the owner and group of the archive file but I was more interested in the extracted files themselves.  In nanliu-staging, you executed the tar command as the specified user - would that work as well here?  The archive resource could take a user / group and pass that to the the Puppet::Util::Execution call?  

Tar files also support the -o option for extraction which would ignore the owner specified within the tar file and use the process owner executing the tar command.  That could help as well.

**Comment by nanliu** [comment]
You can pass custom flags to via extraction_flags. I'll take a look and see what it takes to specify user/group option to the extraction command.

**Comment by mkrakowitzer** [comment]
I don't believe for tar that you can specify a user or a group. The only way is to run the tar command as the user you would prefer. puppet-staging does this by running an exec as the user/group.

I would very much like this feature.

**Comment by elyscape** [comment]
GNU tar supports `--owner` and `--group` flags.

**Comment by elyscape** [comment]
It looks like BSD tar does not, though, so the best option is probably to run the tar command as the desired user/group.

**Comment by mkrakowitzer** [comment]
yeah i am pretty sure --owner and --group does not work as you would expect it too.

**Comment by mkrakowitzer** [comment]
```   --group=NAME
           force NAME as group for added files

  --owner=NAME
           force NAME as owner for added files
```

Having had some experience with this, its only when adding files to an archive and not extracting the files.

**Comment by elyscape** [comment]
Ah, whoops.  Well, either way, it makes more sense to just run the command as the desired user/group, as that'll work on all platforms and is a pretty simple change to make.

**Comment by nanliu** [comment]
The changes require puppet::util::execution to pass in the option uid, gid:
https://github.com/nanliu/puppet-archive/blob/master/lib/puppet_x/bodeco/archive.rb#L41

The changes will be fairly similar to the following:
https://github.com/boxen/puppet-vagrant/blob/master/lib/puppet/provider/vagrant.rb#L19-L30

I'll try to tackle this as time permits, in the mean time if someone needs it sooner, hopefully this provides enough pointers.

**Comment by nanliu** [comment]
I've added support for this. Please test and provide feedback.
