### ISSUE TITLE
Support for puppet://

### ISSUE THREAD

**Issue by mitfik** [nanliu/puppet-archive#42]
Hi 
I could not find any information about supported protocols, and from the code it seems that the is just ftp and http supported right now. Are you planing to add support for puppet:// "protocol"? 

Thanks a lot
br

**Comment by nanliu** [comment]
http://, ftp://, and extraction for local file://. Download of puppet:// is built in to puppet's native file resource.

**Comment by nanliu** [comment]
FYI forge generate documentation from the resource type (so it was not duplicated in the README). If there's any improvements that can be made, let me know: https://forge.puppetlabs.com/nanliu/archive/types

**Comment by nanliu** [comment]
This has been documented in #47.
