### ISSUE TITLE
'7zip' variables incompatible with Puppet 4.0

### ISSUE THREAD

**Issue by antoineco** [nanliu/puppet-archive#43]
With the new parser introduced in Puppet 4.0 variable names are no allowed to start with a digit.

**Comment by nanliu** [comment]
Ok, looks a like I have a few bugs that are breaking changes. I'll create another branch and queue them up for a release.

**Comment by nanliu** [comment]
Thanks for the PR, this will be resolved in #45.

**Comment by nanliu** [comment]
Please review and test 0.3.x branch.
